name: Remover recursos

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3         

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Remover objeto do s3
        run: aws s3 rm "s3://lambda-with-api-gateway-code/lambda.zip"     

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3                 

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./infra 

      - name: Remove estado do objeto da lambda do s3
        run: terraform state rm aws_s3_bucket_object.lambda_zip          

      - name: Destruir Infraestrutura com Terraform
        run: terraform destroy -auto-approve
        working-directory: ./infra